### ISSUE TITLE
location of pre-built binaries

### ISSUE THREAD

**Issue by gregoryaburk** [itsmewes/gotp#1]
readme.md says: "The quickest way to get set up is to download the latest binary from https://github.com/itsmewes/gotp/releases"

that url returns 404 error for me.

**Comment by itsmewes** [comment]
Hi @gregoryaburk 

This is what you should be seeing at the url. I have tried going to https://github.com/itsmewes/gotp/releases in Firefox (Private window) and Chrome (not logged in) and was able to see this page.
![gotp-releases-page](https://user-images.githubusercontent.com/974222/95421061-ed5e4c80-093c-11eb-9045-e0f60e790a60.png)

What happens when you click on the releases header link? Where does that take you to?
![gotp-releases](https://user-images.githubusercontent.com/974222/95421065-f18a6a00-093c-11eb-84f2-941caa8e58f0.png)

**Comment by itsmewes** [comment]
Hi @gregoryaburk 

I looked around and I hadn't added the links correctly in markdown. I have updated the links and they should be working now. Thank you for pointing this out.
